name = "LightQuery"
uuid = "a6f99520-0501-547d-81af-dc7bed1e4d5a"
repo = "https://github.com/bramtayl/LightQuery.jl.git"
version = "0.2.0"
author = ["Brandon Taylor <brandon.taylor221@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Documenter"]
